### ISSUE TITLE
Нужно добавить скролл

### ISSUE THREAD

**Issue by kopylovvlad** [Rarity/y_vas_tire_korotkoe#1]
Если анек длинный, то во второй текст-ареа надо добавить скрол

**Comment by kopylovvlad** [comment]
![Screenshot 2024-12-03 at 13 36 32](https://github.com/user-attachments/assets/7b9a6860-02aa-4f1b-bee9-1387f7d7d3e3)

**Comment by Rarity** [comment]
поправлено
